#English to banana script
from __future__ import print_function

traslateList = {}
traslateList['a'] = "BANANAS"
traslateList['b'] = "BANANAs"
traslateList['c'] = "BANANaS"
traslateList['d'] = "BANANas"
traslateList['e'] = "BANAnAS"
traslateList['f'] = "BANAnAs"
traslateList['g'] = "BANAnaS"
traslateList['h'] = "BANAnas"
traslateList['i'] = "BANaNAS"
traslateList['j'] = "BANaNAs"
traslateList['k'] = "BANaNaS"
traslateList['l'] = "BANaNas"
traslateList['m'] = "BANanAS"
traslateList['n'] = "BANanAs"
traslateList['o'] = "BANanaS"
traslateList['p'] = "BANanas"
traslateList['q'] = "BAnANAS"
traslateList['r'] = "BAnANAs"
traslateList['s'] = "BAnANaS"
traslateList['t'] = "BAnANas"
traslateList['u'] = "BAnAnAS"
traslateList['v'] = "BAnAnAs"
traslateList['w'] = "BAnAnaS"
traslateList['x'] = "BAnAnas"
traslateList['y'] = "BAnaNAS"
traslateList['z'] = "BAnaNAs"
traslateList['A'] = "BAnaNaS"
traslateList['B'] = "BAnaNas"
traslateList['C'] = "BAnanAS"
traslateList['D'] = "BAnanAs"
traslateList['E'] = "BAnanaS"
traslateList['F'] = "BAnanas"
traslateList['G'] = "BaNANAS"
traslateList['H'] = "BaNANAs"
traslateList['I'] = "BaNANaS"
traslateList['J'] = "BaNANas"
traslateList['K'] = "BaNAnAS"
traslateList['L'] = "BaNAnAs"
traslateList['M'] = "BaNAnaS"
traslateList['N'] = "BaNAnas"
traslateList['O'] = "BaNaNAS"
traslateList['P'] = "BaNaNAs"
traslateList['Q'] = "BaNaNaS"
traslateList['R'] = "BaNaNas"
traslateList['S'] = "BaNanAS"
traslateList['T'] = "BaNanAs"
traslateList['U'] = "BaNanaS"
traslateList['V'] = "BaNanas"
traslateList['W'] = "BanANAS"
traslateList['X'] = "BanANAs"
traslateList['Y'] = "BanANaS"
traslateList['Z'] = "BanANas"
traslateList[' '] = "BanAnAS"
traslateList['-1'] = "BanAnAs"
traslateList['0'] = "BanAnaS"
traslateList['1'] = "BanAnas"
traslateList['2'] = "BanaNAS"
traslateList['3'] = "BanaNAs"
traslateList['4'] = "BanaNaS"
traslateList['5'] = "BanaNas"
traslateList['6'] = "BananAS"
traslateList['7'] = "BananAs"
traslateList['8'] = "BananaS"
traslateList['9'] = "Bananas"

traslateList[','] = "bANANAS"
traslateList['.'] = "bANANAs"
traslateList['/'] = "bANANaS"
traslateList[';'] = "bANANas"
traslateList['\''] = "bANAnAS"
traslateList['['] = "bANAnAs"
traslateList[']'] = "bANAnaS"
traslateList['='] = "bANAnas"
traslateList['-'] = "bANaNAS"
traslateList['`'] = "bANaNAs"
traslateList['~'] = "bANaNaS"
traslateList['!'] = "bANaNas"
traslateList['@'] = "bANanAS"
traslateList['#'] = "bANanAs"
traslateList['$'] = "bANanaS"
traslateList['%'] = "bANanas"
traslateList['^'] = "bAnANAS"
traslateList['&'] = "bAnANAs"
traslateList['*'] = "bAnANaS"
traslateList['('] = "bAnANas"
traslateList[')'] = "bAnAnAS"
traslateList['_'] = "bAnAnAs"
traslateList['+'] = "bAnAnaS"
traslateList['{'] = "bAnAnas"
traslateList['}'] = "bAnaNAS"
traslateList['|'] = "bAnaNAs"
traslateList['\\'] = "bAnaNaS"
traslateList[':'] = "bAnaNas"
traslateList['"'] = "bAnanAS"
traslateList['?'] = "bAnanAs"
traslateList['>'] = "bAnanaS"
traslateList['<'] = "bAnanas"

inputString = raw_input()
while (inputString != "exit"):
    for char in inputString:
        try:
            print(traslateList[char], end=' ')
        except:
            print("Character \"" + char + "\" could not be translated")
    print()

    inputString = raw_input()
